version: 2.1

orbs:
    node: circleci/node@4.7
    npm-publisher: uraway/npm-publisher@0.2.0

workflows:
    Test-Lint-Build-All-Versions:
        jobs:
            # Testing code
            - node/test:
                  matrix:
                      parameters:
                          version: ['16.10', '14.17', '12.22']
                  pkg-manager: yarn

            # Linting code
            - node/run:
                  matrix:
                      parameters:
                          version: ['16.10', '14.17', '12.22']
                  pkg-manager: yarn
                  yarn-run: lint

            # Building code
            - node/run:
                  matrix:
                      parameters:
                          version: ['16.10', '14.17', '12.22']
                  pkg-manager: yarn
                  yarn-run: build
    Publish:
        jobs:
            - npm-publisher/publish-from-package-version:
                pre-publish-steps:
                    - run: npm install
                    - run: npm run build
                post-publish-steps:
                    - run: rm ./package-lock.json
                filters: 
                    branches:
                        only:
                            - main
                    tags:
                        only: 
                            - /^v.*/
